
version: 0.2
phases:
  # install:
  #  commands:
  #    - aws cloudformation package --template-file getRiskReport.yaml --s3-bucket adamarla-deployment-generic --output-template-file packaged-template.yaml
  build:
    commands: 
      - echo Hello from Codebuild
      # - that's it
# artifacts:
#  type: zip
#  files:
#    - getRiskReport.yaml
#    - packaged-template.yaml

