AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Description: An AWS Serverless Specification template describing your function.

Resources:

  RiskSummary:
    Type: 'AWS::Serverless::Function'
    Properties:
      FunctionName: 'risk-summary'
      Handler: lambda_function.lambda_handler
      Runtime: python3.6
      CodeUri: src/
      Description: ''
      MemorySize: 128
      Timeout: 3
      Role:
        Fn::Sub: arn:aws:iam::${AWS::AccountId}:role/service-role/defaultRole'
      Events:
        RESTEndPoint:
          Type: Api
          Properties:
            Path: /riskReport
            Method: GET
            RestApiId:
              Ref: RiskReportApi

  RiskReportApi:
    Type: 'AWS::Serverless::Api'
    Properties:
      Name: 'risk-report-api'
#      DefinitionUri: specs/getRiskReport-API-dev01-swagger-apigateway.yaml
      StageName: default
      DefinitionBody:
        swagger: 2.0
        info:
          title:
            Ref: AWS::StackName
        paths:
          "/riskReport":
            get:
              produces:
                - 'application/json'
              x-amazon-apigateway-integration:
                httpMethod: POST
                type: aws_proxy
                uri:
                  Fn::Sub: arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${RiskSummary.Arn}/invocations
