---
swagger: "2.0"
info:
  version: "2019-01-25T17:34:31Z"
  title: "getRiskReport-API"
host: "n9zoyzpsbd.execute-api.us-east-2.amazonaws.com"
basePath: "/dev01"
schemes:
- "https"
paths:
  /getRiskReport:
    get:
      produces:
      - "application/json"
      responses:
        200:
          description: "200 response"
          schema:
            $ref: "#/definitions/Empty"
definitions:
  Empty:
    type: "object"
    title: "Empty Schema"
